Zenith/Controllers/VQWorkFlowController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Zenith.BLL.DTO;
using Zenith.BLL.Interface;
using Zenith.Repository.DomainModels;
using Zenith.Repository.Enums;

namespace Zenith.Controllers
{
    [Authorize]
    public class VQWorkFlowController : BaseController
    {
        private readonly IVendorQualificationWorkFlow _IVendorQualificationWorkFlow;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IWorkFlows _workFlows;
        private readonly IVendorQualificationWorkFlowExecution _vendorQualificationWorkFlowExecution;
        public VQWorkFlowController(IHttpContextAccessor httpContextAccessor,
            SignInManager<ApplicationUser> signInManager,
            IVendorQualificationWorkFlow iVendorQualificationWorkFlow,
            RoleManager<IdentityRole> roleManager,
            IWorkFlows workFlows,
            IVendorQualificationWorkFlowExecution vendorQualificationWorkFlowExecution) : base(httpContextAccessor, signInManager)
        {
            _IVendorQualificationWorkFlow = iVendorQualificationWorkFlow;
            _roleManager = roleManager;
            _workFlows = workFlows;
            _vendorQualificationWorkFlowExecution = vendorQualificationWorkFlowExecution;
        }

        /// <summary>
        /// Adds a new Vendor Qualification WorkFlow based on the provided model and the logged-in user's ID,
        /// and returns the result as a JSON response.
        /// </summary>
        /// <param name="model">The Vendor Qualification WorkFlow data to be added.</param>
        /// <returns>
        /// A JSON result containing the outcome of adding the Vendor Qualification WorkFlow.
        /// </returns>
        [HttpPost]
        public IActionResult AddVQWorkFlow(VendorQualificationWorkFlowDTO model)
        {
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            model.SecurityGroupId = Guid.Parse("4E70A2A0-E668-42D4-A503-0A793799B600");
            return Json(_IVendorQualificationWorkFlow.AddVendorQualificationWorkFlow(model, loggedInUserId));
        }

        /// <summary>
        /// Retrieves the list of Vendor Qualification WorkFlow steps and associated data based on the provided WorkFlow ID,
        /// then returns the data along with the WorkFlow steps and name to the view.
        /// </summary>
        /// <param name="workFlowId">The unique identifier of the WorkFlow (default is empty GUID).</param>
        /// <returns>
        /// A view displaying the list of Vendor Qualification WorkFlow data along with WorkFlow steps and name.
        /// </returns>
        [HttpGet]
        public async Task<IActionResult> VQWorkFlowList(Guid workFlowId = default)
        {
            var workFlowSteps = Enum.GetValues(typeof(WorkFlowEnum))
                .Cast<WorkFlowEnum>()
                .Select(e => new
                {
                    Id = e.ToString(),
                    Name = e.GetStringValue()
                })
                .ToList();

            var workFlow = await _workFlows.GetWorkFlowById(workFlowId);
            ViewBag.WorkFlowStpes = workFlowSteps;
            ViewBag.WorkFlowName = workFlow != null ? workFlow.Name : "";
            ViewBag.workFlowId = workFlowId;
            var data = await _IVendorQualificationWorkFlow.GetVendorQualificationWorkFlow(workFlowId);
            return View(data);
        }

        /// <summary>
        /// Retrieves the detailed view of a specific Vendor Qualification WorkFlow based on the provided ID,
        /// and provides additional data such as role information and WorkFlow steps for display in the view.
        /// </summary>
        /// <param name="vendorQualificationWorkFlowId">The unique identifier of the Vendor Qualification WorkFlow.</param>
        /// <returns>
        /// A view containing the details of the Vendor Qualification WorkFlow along with available role information
        /// and WorkFlow steps.
        /// </returns>
        public async Task<ViewResult> VQWorkFlowViewDetail(Guid vendorQualificationWorkFlowId)
        {
            var data = await _IVendorQualificationWorkFlow.GetVendorQualificationWorkFlowById(vendorQualificationWorkFlowId);
            ViewBag.RoleId = _roleManager.Roles.ToList();
            ViewBag.SecurityGroup = "";
            var workFlowSteps = Enum.GetValues(typeof(WorkFlowEnum))
                .Cast<WorkFlowEnum>()
                .Select(e => new
                {
                    Id = e.ToString(), // Enum name as value
                    Name = e.GetStringValue() // Custom string value
                })
                .ToList();

            ViewBag.WorkFlowStpes = workFlowSteps;

            return View(data);
        }

        /// <summary>
        /// Deletes selected Vendor Qualification WorkFlows based on the provided list of GUIDs, and returns 
        /// the status of the deletion process, including details on any WorkFlows that could not be deleted.
        /// </summary>
        /// <param name="selectedUserGuids">A list of GUIDs representing the Vendor Qualification WorkFlows to be deleted.</param>
        /// <returns>
        /// A JSON response indicating whether the deletion was successful, partially successful, or failed,
        /// along with the names of any WorkFlows that could not be deleted.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> DeleteVQWorkFlow([FromBody] List<Guid> selectedUserGuids)
        {
            try
            {
                var result = await _IVendorQualificationWorkFlow.DeleteVendorQualificationWorkFlow(selectedUserGuids);
                return Ok(new
                {
                    isSuccess = result.isSuccess && result.notDeletedVQWorkFlowNames.Count == 0,
                    PartiallySuccess = result.isSuccess && result.notDeletedVQWorkFlowNames.Count > 0,
                    notDeletedVQWorkFlowNames = result.notDeletedVQWorkFlowNames
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { IsSuccess = false, Message = "An error occurred." });
            }
        }

        /// <summary>
        /// Updates the Vendor Qualification WorkFlow with the given model. If the update is successful, it returns a success message.
        /// If the data provided is invalid, it returns an error message.
        /// </summary>
        /// <param name="model">The VendorQualificationWorkFlowDTO model containing the updated details of the Vendor Qualification WorkFlow.</param>
        /// <returns>
        /// A JSON response indicating whether the update was successful or if there was an error due to invalid data.
        /// </returns>
        [HttpPost]
        public async Task<JsonResult> UpdateVQWorkFlow(VendorQualificationWorkFlowDTO model)
        {
            try
            {
                model.SecurityGroupId = Guid.Parse("4E70A2A0-E668-42D4-A503-0A793799B600");
                if (await _IVendorQualificationWorkFlow.UpdateVendorQualificationWorkFlow(model))
                {
                    return new JsonResult(new { responseCode = 2, SuccessResponse = "Successfully Update Record." });

                }
                return new JsonResult(new { ResponseCode = 1, Response = "Please Ennter Valied Data." });
            }
            catch (Exception ex)
            {
                throw new Exception(ex.ToString());
            }
        }

        /// <summary>
        /// Updates the execution status of the Vendor Qualification WorkFlow from the workbench using the provided model.
        /// If the update is successful, a success message is returned. Otherwise, an error message indicating invalid data is returned.
        /// </summary>
        /// <param name="model">The VendorQualificationWorkFlowExecutionDTO model containing the details of the work flow execution status.</param>
        /// <returns>
        /// A JSON response indicating whether the update was successful or if the data was invalid.
        /// </returns>
        [HttpPost]
        public async Task<JsonResult> UpdateVQWorkFlowExecutionStatus(VendorQualificationWorkFlowExecutionDTO model)
        {
            try
            {
                if (await _vendorQualificationWorkFlowExecution.UpdateVendorQualificationWorkFlowExecutionStatusFromWorkBench(model))
                {
                    return new JsonResult(new { responseCode = 2, SuccessResponse = "Successfully Update Record." });

                }
                return new JsonResult(new { ResponseCode = 1, Response = "Please Ennter Valied Data." });
            }
            catch (Exception ex)
            {
                throw new Exception(ex.ToString());
            }
        }
    }
}

Zenith/Controllers/WorkFlowsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Zenith.BLL.DTO;
using Zenith.BLL.Interface;

namespace Zenith.Controllers
{
    [Authorize]
    public class WorkFlowsController : Controller
    {
        private readonly IWorkFlows _workFlows;

        public WorkFlowsController(IWorkFlows workFlows)
        {
            _workFlows = workFlows;
        }

        /// <summary>
        /// This method returns the view for the Index page. It is typically used to render the default landing page of the application.
        /// </summary>
        /// <returns>Returns the view associated with the Index action.</returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// This method returns the view for adding a new workflow. It is typically used to render the page where users can add workflow details.
        /// </summary>
        /// <returns>Returns the view associated with the AddWorkFlow action.</returns>
        [HttpGet]
        public IActionResult AddWorkFlow()
        {
            return View();
        }

        /// <summary>
        /// This method handles the submission of a new workflow. It receives the workflow data from the user, processes it, and returns a JSON response indicating whether the workflow was created successfully.
        /// </summary>
        /// <param name="model">The data transfer object containing the details of the new workflow to be created.</param>
        /// <returns>Returns a JSON response with the result of the workflow creation process.</returns>
        [HttpPost]
        public IActionResult AddWorkFlow(WorkFlowsDTO model)
        {
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return Json(_workFlows.CreateWorkFlow(model, loggedInUserId));
        }

        /// <summary>
        /// This method retrieves a list of workflows and returns the view to display them. It fetches the data asynchronously and passes it to the view for rendering.
        /// </summary>
        /// <returns>Returns the view displaying the list of workflows.</returns>
        [HttpGet]
        public async Task<IActionResult> WorkFlowList()
        {
            var data = await _workFlows.GetWorkFlows();
            return View(data);
        }

        /// <summary>
        /// This method retrieves the details of a specific workflow by its ID and returns the view to display the details.
        /// </summary>
        /// <param name="WorkFlowId">The unique identifier of the workflow to retrieve.</param>
        /// <returns>Returns the view displaying the details of the specified workflow.</returns>
        public async Task<ViewResult> WorkFlowViewDetail(Guid WorkFlowId)
        {
            var data = await _workFlows.GetWorkFlowById(WorkFlowId);
            return View(data);
        }

        /// <summary>
        /// This method handles the deletion of selected workflows. It receives a list of workflow IDs to be deleted, processes the request, and returns a JSON response indicating the success or failure of the operation.
        /// </summary>
        /// <param name="selectedWorkFlowGuids">A list of unique identifiers for the workflows to be deleted.</param>
        /// <returns>Returns a JSON response indicating whether the deletion was successful, partially successful, or if any workflows were not deleted.</returns>
        [HttpPost]
        public async Task<IActionResult> DeleteWorkFlow([FromBody] List<Guid> selectedWorkFlowGuids)
        {
            try
            {
                var result = await _workFlows.DeleteWorkFlows(selectedWorkFlowGuids);

                return Ok(new
                {
                    IsSuccess = result.isSuccess && result.notDeletedWorkFlowNames.Count == 0,
                    PartiallySuccess = result.isSuccess && result.notDeletedWorkFlowNames.Count > 0,
                    NotDeletedWorkFlows = result.notDeletedWorkFlowNames
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { IsSuccess = false, Message = "An error occurred." });
            }
        }

        /// <summary>
        /// This method handles the update of an existing workflow. It receives the updated workflow data, processes the update, and returns a JSON response indicating whether the update was successful or if there was an issue with the data provided.
        /// </summary>
        /// <param name="model">The data transfer object containing the updated details of the workflow.</param>
        /// <returns>Returns a JSON response indicating whether the workflow was successfully updated or if invalid data was provided.</returns>
        [HttpPost]
        public async Task<JsonResult> UpdateWorkFlow(WorkFlowsDTO model)
        {
            try
            {
                var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (await _workFlows.UpdateWorkFlow(model, loggedInUserId))
                {
                    return new JsonResult(new { responseCode = 2, SuccessResponse = "Successfully Update Record." });

                }
                return new JsonResult(new { ResponseCode = 1, Response = "Please Enters Valid Data." });
            }
            catch (Exception ex)
            {
                throw new Exception(ex.ToString());
            }
        }
    }
}

Zenith/Views/WorkFlows/WorkFlowList.cshtml
@model IEnumerable<Zenith.BLL.DTO.WorkFlowsDTO>
@{
    ViewData["Title"] = "WorkFlow Management";
}

<style>
    .title {
        color: #00387f;
        font-weight: 600;
        text-align: center;
        margin-bottom: 40px;
    }

        .title span {
            color: #C72C1C;
        }

    .btn-delete {
        background-color: #e74c3c; /* Red background */
        color: #fff; /* White text */
        font-weight: bold;
        border: none;
        border-radius: 8px;
        padding: 10px 20px;
        transition: background-color 0.3s ease, transform 0.2s ease;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2); /* Subtle shadow */
    }

        .btn-delete:hover {
            background-color: #c0392b; /* Darker red on hover */
            transform: scale(1.05); /* Slight scale up on hover */
            box-shadow: 0px 6px 8px rgba(0, 0, 0, 0.3); /* More shadow on hover */
        }

        .btn-delete:active {
            background-color: #a93226; /* Even darker red on click */
            transform: scale(0.98); /* Scale down on click */
        }
</style>

<div class="container-fluid">
    <div class="row">
        <!-- sidebar -->
        <div class="col-md-3 col-lg-2 px-0 shadow-sm sidebar">
            <partial name="_Sidebar" />
        </div>

        <div class="col-md-9 col-lg-10 ml-md-auto mt-3">
            <div class="container-fluid">
                <div class="d-flex justify-content-between align-items-center">
                    <h1 class="py-2 mb-0 title">WorkFlow <span> Management</span></h1>
                    <div>
                        <button class="btn btn-outline-info text-dark" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="fas fa-plus"></i> Add New WorkFlow</button>
                        <button class="btn btn-delete" onclick="deleteSelectedWorkFlow()">Delete WorkFlow</button>
                    </div>
                </div>
                <div class="mt-3" style="overflow:auto;height:590px">
                    <table class="table table-striped table-bordered" style="width:125%">
                        <thead class="bg-primary text-white text-center text-nowrap">
                            <tr>
                                <th><input type="checkbox" onchange="selectAllChkbxChangeEvent(this)" /></th>
                                <th><b>Name</b></th>
                                <th><b>Description</b></th>
                                <th><b>Created Date</b></th>
                                <th><b>Created By</b></th>
                                <th><b>Is Active</b></th>
                                <th><b>Is Critical</b></th>
                                <th><b>Action</b></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int index = 1;
                                @foreach (var workFlow in Model)
                                {
                                    <tr>
                                        <td class="text-center">
                                            <a title="View" target="_blank" class="nav-link" asp-controller="WorkFlows" asp-action="WorkFlowViewDetail" asp-route-WorkFlowId="@workFlow.Id">
                                                <input type="checkbox" workFlowId="@workFlow.Id" class="actionCheckboxes" />
                                            </a>
                                        </td>
                                        <td class="text-center">
                                            <a title="View" target="_blank" class="nav-link" asp-controller="VQWorkFlow" asp-action="VQWorkFlowList" asp-route-WorkFlowId="@workFlow.Id">
                                                @workFlow.Name
                                            </a>
                                        </td>
                                        <td class="text-center">@workFlow.Description</td>
                                        <td class="text-center">@workFlow.CreatedOn</td>
                                        <td class="text-center">@workFlow.CreatedBy</td>
                                        <td class="text-center">
                                            @if (workFlow.IsActive)
                                            {
                                                <input type="checkbox" checked disabled />
                                            }
                                            else
                                            {
                                                <input type="checkbox" disabled />
                                            }
                                        </td>
                                        <td class="text-center">
                                            @if (workFlow.IsCritical)
                                            {
                                                <input type="checkbox" checked disabled />
                                            }
                                            else
                                            {
                                                <input type="checkbox" disabled />
                                            }
                                        </td>
                                        <td>
                                            <a title="View" target="_blank" href="/WorkFlows/WorkFlowViewDetail?WorkFlowId=@workFlow.Id" class="btn btn-dark">
                                                <i class="fas fa-eye"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    index++;
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@* Modal *@

<!-- Add User -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width:100%;max-width:768px">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add New WorkFlow</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="addWorkFlow" method="post">
                    <div class="row">
                        <div class="form-group col-md-6 mt-2">
                            <label>Name <span class="text-danger fw-bold">*</span></label>
                            <input type="text" onblur="validateForm(this.value,true,'requiredFullName')" class="form-control mt-2 name" name="Name" placeholder="Name" />
                            <span class="text-danger" id="NameErrorMessage" style="display:none">This field is required</span>
                        </div>
                        <div class="form-group col-md-6 mt-2">
                            <label>Description <span class="text-danger fw-bold">*</span></label>
                            <input type="text" onblur="validateForm(this.value,true,'invalidErrorMessage')" class="form-control mt-2 description" name="Username" placeholder="description" />
                            <span class="text-danger" id="DescriptionErrorMessage" style="display:none">This field is required</span>
                        </div>
                        <div class="form-group col-md-6 mt-2">
                            <label for="IsActive" class="form-label">
                                Is Active <span class="text-danger fw-bold">*</span>
                            </label>
                            <input type="checkbox"
                                   id="IsActive"
                                   class="form-check-input isactive"
                                   name="IsActive" />
                            <span class="text-danger" id="isActiveErrorMessage" style="display:none">This field is required</span>
                        </div>
                        <div class="form-group col-md-6 mt-2">
                            <label for="IsCriticalOnly" class="form-label">
                                Is Critical<span class="text-danger fw-bold">*</span>
                            </label>
                            <input type="checkbox"
                                   id="IsCriticalOnly"
                                   class="form-check-input iscriticalonly"
                                   name="IsCriticalOnly" />
                            <span class="text-danger" id="isCriticalErrorMessage" style="display:none">This field is required</span>
                        </div>
                      
                    </div>
                    <div class="modal-footer mt-3">
                        <button type="button" class="btn btn-primary" onclick="addWorkFlow()">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="~/lib/jquery/common.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    
    //Update user funtion
    function addWorkFlow() {
        let name = $('#addWorkFlow .name').val();
        let isactive = $('#addWorkFlow .isactive').prop('checked');
        let iscriticalonly = $('#addWorkFlow .iscriticalonly').prop('checked');
        let description = $('#addWorkFlow .description').val();

        if ((!validateForm(name, true, 'requiredFullName')) || (!validateForm(description, true, 'invalidErrorMessage')))
            return false;


        $.ajax({
            url: '/WorkFlows/AddWorkFlow',
            type: 'POST',
            data: {
                name: name,
                isactive: isactive,
                IsCritical: iscriticalonly,
                description: description
            },
            success: function (resp) {
                window.location.reload();
            }
        });
    }

    function changeActive(event, workFlowId) {
        const isCheck = event.target.checked;
        updateUser(isCheck, workFlowId);
    }

    function selectAllChkbxChangeEvent(thisEvent) {
        $(".actionCheckboxes").each(function () {
            $(this).prop('checked', $(thisEvent).is(":checked"));
        });
    }

    function deleteSelectedWorkFlow() {
        let selectedGuids = [];

        $(".actionCheckboxes:checked").each(function () {
            selectedGuids.push($(this).attr('workFlowId'));
        });

        if(selectedGuids.length === 0){
            Swal.fire({
                icon : "warning",
                text : "Please select a record to delete.",
                showConfirmButton : true,
            });
            return;
        }

        Swal.fire({
            title: 'Are you sure?',
            text: 'Do you really want to delete the selected workflows?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel',
        }).then((result) => {
            if (result.value === true) {
                $.ajax({
                    type: "POST",
                    url: "/WorkFlows/DeleteWorkFlow",
                    data: JSON.stringify(selectedGuids),
                    contentType: "application/json; charset=utf-8",
                    success: function (response) {
                         if (response.isSuccess) {
                            Swal.fire({
                                icon: "success",
                                text: "Selected workflows deleted successfully!",
                                showConfirmButton: false,
                                timer: 1500,
                            }).then(() => {
                                window.location.reload();
                            });
                        } else if (response.partiallySuccess) {
                            Swal.fire({
                                icon: "info",
                                title: "Deletion Failed",
                                html: `Some workflows could not be deleted, Please deactivate the workflows :${response.notDeletedWorkFlows.map(w => `${w}`).join('')}`,
                                showConfirmButton: true,
                            }).then(() => {
                                window.location.reload();
                            });
                        } else {
                            Swal.fire({
                                icon: "error",
                                title: "Deletion Failed",
                                text: `The following workflows cannot be deleted. Please deactivate the workflows:${response.notDeletedWorkFlows.map(w => `${w}`).join(', ')}`,
                                showConfirmButton: true,
                            });
                        }
                    },
                    error: function () {
                        Swal.fire({
                            icon: "error",
                            text: "An error occurred. Please try again.",
                            showConfirmButton: true,
                        });
                    }
                });
            }
        });
    }

</script>