Zenith/Controllers/AppRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Zenith.Repository.DomainModels;

namespace Zenith.Controllers
{
    [Authorize]
    public class AppRolesController : BaseController
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public AppRolesController(IHttpContextAccessor httpContextAccessor,
            SignInManager<ApplicationUser> signInManager,
            RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> UserManager)
        : base(httpContextAccessor, signInManager)
        {
            _roleManager = roleManager;
        }

        /// <summary>
        /// This method retrieves a list of all roles in the system and returns the view to display them.
        /// </summary>
        /// <returns>Returns the view displaying the list of roles.</returns>
        [HttpGet]
        public ActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }

        /// <summary>
        /// This method retrieves and returns a list of all roles in the system.
        /// </summary>
        /// <returns>Returns a list of all roles in the system as a list of <see cref="IdentityRole"/> objects.</returns>
        [HttpGet]
        public List<IdentityRole> GetRoles()
        {
            var roles = _roleManager.Roles.ToList();
            return roles;
        }

        /// <summary>
        /// This method adds a new role to the system if the role does not already exist.
        /// It checks for the role's existence, and if not found, creates a new role and redirects to the index page.
        /// </summary>
        /// <param name="model">The role data transfer object containing the details of the role to be added.</param>
        /// <returns>Redirects to the index page after attempting to add the new role.</returns>
        public async Task<ActionResult> AddNewRole(IdentityRole model)
        {
            if (!await _roleManager.RoleExistsAsync(model.Name))
            {
                var newRole = new ApplicationRoles
                {
                    Name = model.Name,
                };

                await _roleManager.CreateAsync(newRole);
            }
            return RedirectToAction("Index");
        }

        /// <summary>
        /// This method deletes a role by its unique ID. It checks if the role exists, deletes it if found, and redirects to the index page.
        /// If an error occurs, it throws the exception.
        /// </summary>
        /// <param name="roleID">The unique identifier of the role to be deleted.</param>
        /// <returns>Redirects to the index page after attempting to delete the specified role.</returns>
        [HttpGet]
        public async Task<IActionResult> DeleteById(string roleID)
        {
            try
            {
                var deleteRoleObj = _roleManager.Roles.Where(x => x.Id == roleID).FirstOrDefault();
                if (deleteRoleObj != null)
                {
                    await _roleManager.DeleteAsync(deleteRoleObj);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

    }
}

Zenith/Controllers/SettingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Zenith.BLL.DTO;
using Zenith.BLL.Interface;
using Zenith.Repository.DomainModels;

namespace Zenith.Controllers
{
    [Authorize]
    public class SettingController : BaseController
    {
        private readonly ISetting _ISetting;
        private readonly IVacationRequests _IVacationRequests;
        private readonly IUser _IUser;
        private readonly SignInManager<ApplicationUser> _SignInManager;
        public SettingController(IHttpContextAccessor httpContextAccessor, ISetting ISetting, IVacationRequests iVacationRequests, IUser Iuser,
            SignInManager<ApplicationUser> signInManager) : base(httpContextAccessor, signInManager)
        {
            _ISetting = ISetting;
            _SignInManager = signInManager;
            _IUser = Iuser;
            _IVacationRequests = iVacationRequests;
        }

        /// <summary>
        /// This method retrieves the details of the logged-in user by their unique ID and returns the view to display the user information.
        /// </summary>
        /// <returns>Returns the view displaying the details of the logged-in user.</returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var data = await _IUser.GetUserByIdAsync(loggedInUserId);
            return View(data);
        }

        /// <summary>
        /// This method handles the process of changing the user's password. It validates the current password and updates it with the new password for the logged-in user.
        /// </summary>
        /// <param name="currentPassword">The current password of the user.</param>
        /// <param name="newPassword">The new password to set for the user.</param>
        /// <returns>Returns a string indicating the result of the password change process.</returns>
        public async Task<string> ChangePassword(string currentPassword, string newPassword)
        {
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return await _ISetting.ChangePassword(currentPassword, newPassword, loggedInUserId);
        }

        /// <summary>
        /// This method handles the addition of vacation requests. It receives vacation request data and adds it for the logged-in user.
        /// </summary>
        /// <param name="vacationRequestsDTO">The data transfer object containing the details of the vacation request.</param>
        /// <returns>Returns an integer indicating the result of the vacation request addition process (e.g., success or failure status).</returns>
        public async Task<int> AddVacationRequests(VacationRequestsDTO vacationRequestsDTO)
        {
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return await _IVacationRequests.AddVacationRequests(vacationRequestsDTO, loggedInUserId);
        }

        /// <summary>
        /// This method retrieves a list of vacation requests for the logged-in user, filtered by a start and end date. If no dates are provided, it defaults to a 60-day range ending today. The result is returned as a partial view.
        /// </summary>
        /// <param name="filterStartDate">The start date for filtering vacation requests (optional). If not provided, defaults to 60 days before today.</param>
        /// <param name="filterEndDate">The end date for filtering vacation requests (optional). If not provided, defaults to today.</param>
        /// <returns>Returns a partial view displaying the list of vacation requests within the specified date range.</returns>
        public async Task<IActionResult> _VacationRequestsApprovalListPartialView(DateTime? filterStartDate = null, DateTime? filterEndDate = null)
        {
            var loggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            DateTime todayDate = DateTime.Now;
            if (filterStartDate == null)
                filterStartDate = todayDate.AddDays(-60);
            if (filterEndDate == null)
                filterEndDate = todayDate;
            var lists = await _IVacationRequests.GetAccountVacationRequests(loggedInUserId, Convert.ToDateTime(filterStartDate), Convert.ToDateTime(filterEndDate));
            return PartialView(lists);
        }
    }
}

Zenith/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Transactions;
using Zenith.BLL.DTO;
using Zenith.BLL.Interface;
using Zenith.Repository.DomainModels;
using Zenith.Repository.Enums;

namespace Zenith.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {
        private readonly IUser _IUser;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IDropdownList _IDropdownList;
        private readonly IVacationRequests _iVacationRequests;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IVendorQualificationWorkFlow _vendorQualificationWorkFlow;
        private readonly ISecurityGroup _securityGroup;
        private readonly ISecurityGroupUsersLogic _securityGroupUsersLogic;

        public UserController(IUser IUser, IHttpContextAccessor httpContextAccessor,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IDropdownList iDropdownList,
            RoleManager<IdentityRole> roleManager,
            IVacationRequests iVacationRequests,
            IVendorQualificationWorkFlow vendorQualificationWorkFlow,
            ISecurityGroup securityGroup,
            ISecurityGroupUsersLogic securityGroupUsersLogic) : base(httpContextAccessor, signInManager)
        {
            _userManager = userManager;
            _IUser = IUser;
            _IDropdownList = iDropdownList;
            _roleManager = roleManager;
            _iVacationRequests = iVacationRequests;
            _vendorQualificationWorkFlow = vendorQualificationWorkFlow;
            _securityGroup = securityGroup;
            _securityGroupUsersLogic = securityGroupUsersLogic;
        }

        /// <summary>
        /// Retrieves a list of users and reporting managers, and passes them to the view.
        /// </summary>
        /// <returns>A view displaying the list of users and reporting managers.</returns>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var data = _IUser.GetUsers();
            ViewBag.ReportingManagerList = await _IUser.GetReportingManagersAsync();
            return View(data);
        }

        /// <summary>
        /// Retrieves and prepares data for displaying user details, including roles, countries, departments, branches, reporting managers, and assigned security groups.
        /// </summary>
        /// <param name="userId">The ID of the user whose details are being retrieved.</param>
        /// <returns>A view displaying the user's details with dropdown lists for roles, countries, departments, branches, and reporting managers.</returns>
        [HttpGet]
        public async Task<IActionResult> UserViewTemplate(string userId)
        {
            try
            {
                var data = await _IUser.GetUserByIdAsync(userId);

                if (data == null)
                {
                    data = new GetUserListDTO();
                    ViewBag.AddMode = true;
                }

                data.CountryList = _IDropdownList.GetDropdownByName(nameof(DropDownListsEnum.COUNTRY));
                data.DepartmentList = _IDropdownList.GetDropdownByName(nameof(DropDownListsEnum.DEPARTMENTS));
                data.BranchList = _IDropdownList.GetDropdownByName(nameof(DropDownListsEnum.BRANCH));
                data.RolesList = _roleManager.Roles.ToList();
                data.ReportingMangerList = await _IUser.GetReportingManagersAsync();
                data.AssignedSecurityGroups = await _securityGroup.GetSecurityGroupsAssignedToUser(userId);
                return View(data);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        /// <summary>
        /// Updates user information including roles, assigned security groups, and vacation requests. Handles checks for active status and pending work.
        /// </summary>
        /// <param name="model">The model containing updated user information.</param>
        /// <returns>A JSON response indicating the result of the update operation.</returns>
        [HttpPost]
        public async Task<JsonResult> UpdateUser(RegisterUserModel model)
        {
            try
            {
                if (!model.IsActive)
                {
                    var allReportingUserToThisUser = await _IUser.GetAllUsersReportingToThisUser(model.userId);
                    if (allReportingUserToThisUser.Any())
                    {
                        string commaSeparatedNames = string.Join(", ", allReportingUserToThisUser.Select(user => user.FullName));
                        return new JsonResult(new { ResponseCode = 1, Response = commaSeparatedNames });
                    }
                }

                var user = _userManager.Users.FirstOrDefault(x => x.Id == model.userId);

                if (user == null)
                {
                    return new JsonResult(new { ResponseCode = 2, Response = string.Empty });
                }

                var roleNames = await _userManager.GetRolesAsync(user);
                var roleIds = _roleManager.Roles
                                          .Where(role => roleNames.Contains(role.Name))
                                          .Select(role => role.Id)
                                          .ToList();

                if (!roleIds.Contains(model.RoleId))
                {
                    if (await _vendorQualificationWorkFlow.UserAnyWorkIsPending(model.userId))
                    {
                        return new JsonResult(new { ResponseCode = 3, Response = string.Empty });
                    }
                }

                await _securityGroupUsersLogic.RemoveAllSecurityGroupUsersAssignedToUserID(model.userId);
                var loginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (model.AssignedSecurityGroups != null)
                {
                    foreach (var securityGroupId in model.AssignedSecurityGroups)
                    {
                        var securityGroupUsers = new SecurityGroupUsersDTO
                        {
                            UserId = model.userId,
                            SecurityGroupId = securityGroupId,
                            CreatedBy = loginUserId,
                            CreatedOn = DateTime.Now,
                        };
                        await _securityGroupUsersLogic.AddSecurityGroupUsers(securityGroupUsers);
                    }
                }
                await _IUser.UpdateUser(model);

                if (!model.IsActive)
                {
                    await _iVacationRequests.CancelAllActiveVacationRequestsByUserId(model.userId);
                }

                return new JsonResult(new { ResponseCode = 2, Response = string.Empty });
            }
            catch (Exception ex)
            {
                throw new Exception(ex.ToString());
            }
        }

        /// <summary>
        /// Retrieves a list of users.
        /// </summary>
        /// <returns>A list of users as GetUserListDTO objects.</returns>
        [HttpGet]
        public List<GetUserListDTO> GetUsers()
        {
            return _IUser.GetUsers();
        }

        /// <summary>
        /// Retrieves a list of active users and returns their Id and FullName in a structured JSON format.
        /// </summary>
        /// <returns>
        /// A JsonResult containing a list of active users with their Id and FullName.
        /// </returns>
        [HttpGet]
        public JsonResult GetUsersJsonList()
        {
            var users = _IUser.GetUsers(); // Fetch users from the IUser service
            var activeUsers = users.Where(x => x.IsActive).Select(x => new { x.Id, x.FullName }).ToList();
            return new JsonResult(activeUsers, new Newtonsoft.Json.JsonSerializerSettings
            {
                Formatting = Newtonsoft.Json.Formatting.Indented
            });
        }

        /// <summary>
        /// Asynchronously retrieves a list of reporting managers from the IUser service.
        /// </summary>
        /// <returns>
        /// A list of <see cref="ApplicationUser"/> objects representing the reporting managers.
        /// </returns>
        [HttpGet]
        public async Task<List<ApplicationUser>> GetReportingManagersAsync()
        {
            var reportingManagerList = await _IUser.GetReportingManagersAsync();
            return reportingManagerList;
        }

        /// <summary>
        /// Asynchronously adds a new user using the provided <see cref="RegisterUserModel"/>.
        /// </summary>
        /// <param name="model">The user details to be added.</param>
        /// <returns>
        /// A string response indicating the result of the operation.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> AddNewUser(RegisterUserModel model)
        {
            try
            {
                var requestScheme = Request.Scheme;
                var userDetails = await _IUser.AddNewUser(model, Url, requestScheme);

                var loginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (userDetails.isSuccess && model.AssignedSecurityGroups != null)
                {
                    foreach (var securityGroupId in model.AssignedSecurityGroups)
                    {
                        var securityGroupUsers = new SecurityGroupUsersDTO
                        {
                            UserId = userDetails.userId,
                            SecurityGroupId = securityGroupId,
                            CreatedBy = loginUserId,
                            CreatedOn = DateTime.Now,
                        };

Zenith/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zenith</title>
    <link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="/limonte-sweetalert2/sweetalert2.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Zenith.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar container-fluid navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Zenith</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <footer class="container-fluid border-top footer text-center">
            &copy; 2024 - Zenith - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/limonte-sweetalert2/sweetalert2.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Zenith/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZENITH</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/limonte-sweetalert2/sweetalert2.css" rel="stylesheet" />
    @RenderSection("Styles", required: false)
</head>
<style>
    body {
        margin-bottom:0;
    }

    ._form-05-box {
        width: 450px;
        max-width: 100%;
        position: relative;
        display: block;
        margin: 20px auto;
        background: #fff;
        border-radius: 6px;
        z-index: 3;
        padding: 0 15px;
    }

    .main-head h4 {
        color: #c32f1d;
        font-weight: 600;
        margin: 5px 0 0 0;
    }
    ._mn_df {
        padding: 40px 15px 40px;
        background: #fff;
        /*border-top-right-radius: 6px;
        border-bottom-right-radius: 6px;*/
        border-radius: 10px;
        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        display: block;
    }
    ._btn_04 {
        display: inline-block;
        width: 100%;
        padding: 12px 0px;
        background: #063d84;
        border-radius: 5px;
        text-align: center;
        font-size: 16px;
        color: #fff;
    }








    .loginBackgrndImg {
        background: url("/images/manufacturing.jpg") center center no-repeat !important;
        background-size: 100% 100% !important;
        height: 100vh;
    }
</style>
<body>
    <main role="main">
        <div class="appoved-banner loginBackgrndImg">
            @RenderBody()
        </div>
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/fontawesome.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/TypeAhead.js"></script>
    <script src="~/limonte-sweetalert2/sweetalert2.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Zenith/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNetCore.Identity

@{
    var currentController = ViewContext.RouteData.Values["controller"].ToString();
    var currentAction = ViewContext.RouteData.Values["action"].ToString();
}

<div class="list-group rounded-0">
    <a asp-controller="Home" asp-action="Index" class="list-group-item py-3 list-group-item-action @(currentController == "Home" && currentAction == "Index" ? "active" : "") border-0 d-flex align-items-center">
        <i class="fas fa-tachometer-alt me-2"></i>
        <span class="ml-2">Dashboard</span>
    </a>
    <a asp-controller="Manufacturer" asp-action="Index" class="list-group-item py-3 list-group-item-action @(currentController == "Manufacturer" && currentAction == "Index" ? "active" : "") border-0 align-items-center">
        <i class="fas fa-industry me-2"></i>
        <span class="ml-2">Manufacturer</span>
    </a>
    <a asp-controller="Vendors" asp-action="Index" class="list-group-item py-3 list-group-item-action @(currentController == "Vendors" && currentAction == "Index" ? "active" : "") border-0 align-items-center">
        <i class="fas fa-industry me-2"></i>
        <span class="ml-2">Vendor Initialization</span>
    </a>
    <a asp-area="User Management" asp-controller="User" asp-action="Index" class="list-group-item py-3 list-group-item-action @(currentController == "User" && currentAction == "Index" ? "active" : "") border-0 align-items-center">
        <i class="far fa-user me-2"></i>
        <span class="ml-2">User Management</span>
    </a>
    @if (User.IsInRole("Admin"))
    {
        <ul class="submenu">
            <li>
                <a asp-area="User Management" asp-controller="SecurityGroup" asp-action="Index" class="list-group-item py-3 list-group-item-action @(currentController == "SecurityGroup" && currentAction == "Index" ? "active" : "") border-0 align-items-center">
                    <i class="far fa-user-plus me-2"></i>
                    <span class="ml-2">Security Group</span>
                </a>
            </li>
        </ul>
    }
   @*  <a asp-area="Vendor Qualification Work Flow" asp-controller="VQWorkFlow" asp-action="VQWorkFlowList" class="list-group-item py-3 list-group-item-action @(currentController == "VQWorkFlow" && currentAction == "AddVQWorkFlow" ? "active" : "") border-0 align-items-center">
        <i class="far fa-user me-2"></i>
        <span class="ml-2">Vendor Qualification Work Flow</span>
    </a> *@
    <a asp-area="Work Flow" asp-controller="WorkFlows" asp-action="WorkFlowList" class="list-group-item py-3 list-group-item-action @(currentController == "WorkFlows" && currentAction == "WorkFlowList" ? "active" : "") border-0 align-items-center">
        <i class="far fa-user me-2"></i>
        <span class="ml-2">Work Flows</span>
    </a>
    @if (User.IsInRole("Vendor Manager"))
    {
        <a asp-area="Manager Workbench" asp-controller="Workbench" asp-action="Index" class="list-group-item py-3 list-group-item-action @(currentController == "Workbench" && currentAction == "Index" ? "active" : "") border-0 align-items-center">
            <i class="far fa-user me-2"></i>
            <span class="ml-2">Manager Workbench</span>
        </a>
    }
   
    @if (User.IsInRole("Vendor Officer"))
    {
        <a asp-area="Manager Workbench" asp-controller="Workbench" asp-action="OfficerWorkbench" class="list-group-item py-3 list-group-item-action @(currentController == "Workbench" && currentAction == "OfficerWorkbench" ? "active" : "") border-0 align-items-center">
            <i class="far fa-user me-2"></i>
            <span class="ml-2">Officer Workbench</span>
        </a>
    }
    <a class="list-group-item py-3 list-group-item-action border-0 align-items-center" data-bs-toggle="collapse" href="#settingDropdown" role="button" aria-expanded="false" aria-controls="settingDropdown">
        <i class="fas fa-wrench me-2"></i>
        <span class="ml-2">Account Setting</span>
    </a>
    <div class="collapse" id="settingDropdown">
        <div class="card card-body">
            <a asp-controller="Setting" asp-action="Index" class="list-group-item py-3 list-group-item-action @(currentController == "Setting" && currentAction == "Index" ? "active" : "") border-0 align-items-center">
                <span class="bi bi-box"></span>
                <span class="ml-2">My account</span>
            </a>
            <a asp-controller="DropdownList" asp-action="Index" class="list-group-item py-3 list-group-item-action @(currentController == "DropdownList" && currentAction == "Index" ? "active" : "") border-0 align-items-center">
                <span class="bi bi-box"></span>
                <span class="ml-2">Dropdown</span>
            </a>
            <a asp-controller="AppRoles" asp-action="Index" class="list-group-item py-3 list-group-item-action @(currentController == "AppRoles" && currentAction == "Index" ? "active" : "") border-0 align-items-center">
                <span class="bi bi-box"></span>
                <span class="ml-2">Role</span>
            </a>
        </div>
    </div>
    
</div>