Zenith/Controllers/SecurityGroupController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Zenith.BLL.DTO;
using Zenith.BLL.Interface;
using Zenith.Repository.DomainModels;

namespace Zenith.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SecurityGroupController : BaseController
    {
        private readonly ISecurityGroup _securityGroup;
        private readonly IFields _fields;
        private readonly ISecurityGroupUsersLogic _securityGroupUsersLogic;

        public SecurityGroupController(IHttpContextAccessor httpContextAccessor,
            SignInManager<ApplicationUser> signInManager,
            ISecurityGroup securityGroup,
            IFields fields,
            ISecurityGroupUsersLogic securityGroupUsersLogic) : base(httpContextAccessor, signInManager)
        {
            _securityGroup = securityGroup;
            _fields = fields;
            _securityGroupUsersLogic = securityGroupUsersLogic;
        }

        /// <summary>
        /// Retrieves a list of all security groups asynchronously and returns the view displaying the list.
        /// </summary>
        /// <returns>view with the list of security groups.</returns>
        public async Task<IActionResult> Index()
        {
            var list = await _securityGroup.GetAllSecurityGroups();
            return View(list);
        }

        /// <summary>
        /// Searches for security groups based on the specified field name and search text, 
        /// retrieves the matching results asynchronously, and returns a partial view with the list.
        /// </summary>
        /// <param name="fieldName">The name of the field to search on.</param>
        /// <param name="searchText">The text to search for within the specified field.</param>
        /// <returns>A PartialViewResult displaying the filtered list of security groups.</returns>
        public async Task<IActionResult> SearchSecurityGroupList(string fieldName, string searchText)
        {
            var list = await _securityGroup.GetAllSecurityGroups(null, fieldName, searchText);

            return PartialView("_SecurityGroupList", list);
        }

        /// <summary>
        /// Retrieves a list of active security groups asynchronously, formats them into a JSON object, 
        /// and returns the result. Only groups with an active status are included.
        /// </summary>
        /// <returns>A JsonResult containing a formatted list of active security groups with their ID and Name.</returns>

        [AllowAnonymous]
        [HttpGet]
        public async Task<JsonResult> GetSecurityGroupJsonList()
        {
            var securityGroups = await _securityGroup.GetAllSecurityGroups(); ; // Fetch users from the IUser service
            var activeSecurityGroups = securityGroups.Where(x => x.IsActive).Select(x => new { x.Id, x.Name }).ToList();
            return new JsonResult(activeSecurityGroups, new Newtonsoft.Json.JsonSerializerSettings
            {
                Formatting = Newtonsoft.Json.Formatting.Indented
            });
        }

        /// <summary>
        /// Initializes the Add Security Group view  and Fields property with a list of all fields retrieved asynchronously
        /// </summary>
        /// <returns>view with the initialized model.</returns>
        [HttpGet]
        public async Task<IActionResult> AddSecurityGroup()
        {
            var model = new SecurityGroupsDTO()
            {
                Fields = await _fields.GetAllFields()
            };

            return View(model);
        }

        /// <summary>
        /// Adds a new security group and assigns users to it.
        /// </summary>
        /// <param name="model">The security group data transfer object containing the details of the new security group.</param>
        /// <returns>A JSON response indicating success or failure.</returns>
        /// <exception cref="ArgumentNullException">Thrown if the model is null.</exception>
        [HttpPost]
        public async Task<IActionResult> AddSecurityGroup(SecurityGroupsDTO model)
        {
            var duplicateNameAndCode = await _securityGroup.IsDuplicateSecurityGroup(model);
            if (duplicateNameAndCode != 0)
            {
                return new JsonResult(new { ResponseCode = duplicateNameAndCode, message = "Please reenter data." });
            }

            var loginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            model.CreatedBy = loginUserId;
            var securityGroupId = await _securityGroup.AddSecurityGroup(model);

            if (model.AssignedUserIds != null)
            {
                foreach (var userId in model.AssignedUserIds)
                {
                    var securityGroupUsers = new SecurityGroupUsersDTO
                    {
                        UserId = userId.ToString(),
                        SecurityGroupId = securityGroupId,
                        CreatedBy = loginUserId,
                        CreatedOn = DateTime.Now,
                    };
                    await _securityGroupUsersLogic.AddSecurityGroupUsers(securityGroupUsers);
                }
            }

            return new JsonResult(new { ResponseCode = 0, message = "Security group is created successfully." });
        }

        /// <summary>
        /// Copy of existing security group. then saves same security group along with its assigned users.
        /// </summary>
        /// <param name="model">The SecurityGroupsDTO model containing security group details and assigned user IDs.</param>
        /// <returns>
        /// A JsonResult indicating the operation's success or failure, including an appropriate response code 
        /// and message.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> CopySecurityGroup([FromBody] List<Guid> selectedSecurityGroupGuids)
        {
            try
            {
                var loginUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var result = await _securityGroup.CopySecurityGroup(selectedSecurityGroupGuids, loginUserId);

                return Ok(new
                {
                    isSuccess = result.isSuccess && result.notCopySecurityGroupNames.Count == 0,
                    PartiallySuccess = result.isSuccess && result.notCopySecurityGroupNames.Count > 0,
                    notCopySecurityGroupNames = result.notCopySecurityGroupNames,
                    copySecurityGroupId = result.copiedSecurityGroupId,
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { IsSuccess = false, Message = "An error occurred." });
            }
        }

        /// <summary>
        /// Deletes a list of security groups based on their GUIDs. Returns the operation's success status, 
        /// including details about any security groups that could not be deleted.
        /// </summary>
        /// <param name="selectedSecurityGroupGuids">A list of GUIDs representing the security groups to be deleted.</param>
        /// <returns>
        /// An OkObjectResult with a response indicating whether the operation was fully or partially successful, 
        /// and a list of security group names that could not be deleted. Returns a 500 status code with an error message if an exception occurs.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> DeleteSecurityGroup([FromBody] List<Guid> selectedSecurityGroupGuids)
        {
            try
            {
                var result = await _securityGroup.DeleteSecurityGroup(selectedSecurityGroupGuids);
                return Ok(new
                {
                    isSuccess = result.isSuccess && result.notDeletedSecurityGroupNames.Count == 0,
                    PartiallySuccess = result.isSuccess && result.notDeletedSecurityGroupNames.Count > 0,
                    notDeletedSecurityGroupNames = result.notDeletedSecurityGroupNames
                });
            }
            catch (Exception)
            {
                return StatusCode(500, new { IsSuccess = false, Message = "An error occurred." });
            }
        }

        /// <summary>
        /// Updates the status of selected security groups to either active or inactive based on the provided status.  
        /// Returns the operation's success status, including details about any security groups that could not be updated.
        /// </summary>
        /// <param name="selectedSecurityGroupGuids">A list of GUIDs representing the security groups to update.</param>
        /// <param name="isActive">A boolean indicating whether to activate or deactivate the selected security groups.</param>
        /// <returns>
        /// An OkObjectResult with a response indicating whether the operation was fully or partially successful,  
        /// and a list of security group names that could not be updated. Returns a 500 status code with an error message if an exception occurs.
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> UpdateSecurityGroupStatus(List<Guid> selectedSecurityGroupGuids, bool isActive)
        {
            try
            {
                var result = await _securityGroup.UpdateSecurityGroupToActive(selectedSecurityGroupGuids, isActive);
                return Ok(new
                {
                    isSuccess = result.isSuccess && result.notUpdatedSecurityGroupNames.Count == 0,
                    PartiallySuccess = result.isSuccess && result.notUpdatedSecurityGroupNames.Count > 0,
                    notUpdatedSecurityGroupNames = result.notUpdatedSecurityGroupNames
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { IsSuccess = false, Message = "An error occurred." });
            }
        }

        /// <summary>

Zenith/Views/SecurityGroup/SecurityGroupTemplate.cshtml
@model Zenith.BLL.DTO.SecurityGroupsDTO
@{
    ViewData["Title"] = "Security Group detail";
}

<style>
    .title {
        color: #00387f;
        font-weight: 600;
        text-align: center;
        margin-bottom: 40px;
    }

        .title span {
            color: #C72C1C;
        }
</style>

<div class="container-fluid">
    <div class="row">
        <!-- sidebar -->
        <div class="col-md-3 col-lg-2 px-0 shadow-sm sidebar">
            <partial name="_Sidebar" />
        </div>

        <div class="col-md-9 col-lg-10 ml-md-auto mt-3">
            <div class="container">
                <div class="d-flex justify-content-between align-items-center">
                    <h1 class="py-2 mb-0 title">Security Group<span> detail</span></h1>
                   @*  <div>
                        <button class="btn btn-outline-info text-dark" id="showEditModeBTN" onclick="showEditMode()"><i class="fas fa-pencil-alt"></i> Edit Work Flow</button>
                        <button type="button" class="btn btn-primary" id="hideSaveBTN" onclick="updateWorkFlow('@Model.Id')">Save</button>
                        <button type="button" class="btn secondary-outline" id="hideEditModeBTN" onclick="hideEditMode()">Cancel</button>
                    </div> *@
                </div>

                <!-- Add User -->
                <div class="" id="">
                    <div class="modal-dialog" style="width:100%;max-width:1000px">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">View profile detail</h5>
                            </div>
                            <div class="modal-body">
                                <form id="editMode" method="post">
                                    <div class="row">
                                        <div class="form-group col-md-6 mt-2">
                                            <label>Name <span class="text-danger fw-bold">*</span></label>
                                            <input type="text" onblur="validateForm(this.value,true,'requiredFullName')" class="editFormFields form-control mt-2 name" name="Name" value="@Model.Name" placeholder="Name" />
                                            <span class="text-danger" id="nameFullName" style="display:none">This field is required</span>
                                        </div>
                                        <div class="form-group col-md-6 mt-2">
                                            <label>SecurityGroupCode <span class="text-danger fw-bold">*</span></label>
                                            <input type="text" onblur="validateForm(this.value,true,'invalidErrorMessage')" class=" editFormFields form-control mt-2 description" name="Description" value="@Model.SecurityGroupCode" placeholder="Description" />
                                            <span class="text-danger" id="DescriptionErrorMessage" style="display:none">This field is required</span>
                                        </div>
                                        <div class="form-group col-md-6 mt-2">
                                            <label>Description <span class="text-danger fw-bold">*</span></label>
                                            <input type="text" onblur="validateForm(this.value,true,'invalidErrorMessage')" class=" editFormFields form-control mt-2 description" name="Description" value="@Model.Description" placeholder="Description" />
                                            <span class="text-danger" id="DescriptionErrorMessage" style="display:none">This field is required</span>
                                        </div>
                                        <div class="form-group col-md-6 mt-2">
                                            <label>IsActive <span class="text-danger fw-bold">*</span></label>
                                            <input type="text" onblur="validateForm(this.value,true,'invalidErrorMessage')" class=" editFormFields form-control mt-2 description" name="Description" value="@Model.IsActive" placeholder="Description" />
                                            <span class="text-danger" id="DescriptionErrorMessage" style="display:none">This field is required</span>
                                        </div>
                                        <div class="form-group col-md-6 mt-2">
                                            <label>CreatedBy <span class="text-danger fw-bold">*</span></label>
                                            <input type="text" onblur="validateForm(this.value,true,'invalidErrorMessage')" class=" editFormFields form-control mt-2 description" name="Description" value="@Model.CreatedByName" placeholder="Description" />
                                            <span class="text-danger" id="DescriptionErrorMessage" style="display:none">This field is required</span>
                                        </div>
                                        <div class="form-group col-md-6 mt-2">
                                            <label>Modified By <span class="text-danger fw-bold">*</span></label>
                                            <input type="text" onblur="validateForm(this.value,true,'invalidErrorMessage')" class=" editFormFields form-control mt-2 description" name="Description" value="@Model.ModifiedByName" placeholder="Description" />
                                            <span class="text-danger" id="DescriptionErrorMessage" style="display:none">This field is required</span>
                                        </div>

                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/common.js"></script>

<script>
    $("#hideEditModeBTN").hide();
    $("#hideSaveBTN").hide();
    formEnable(true);

    function showEditMode() {
        $("#hideEditModeBTN").show();
        $("#hideSaveBTN").show();
        $("#showEditModeBTN").hide();
        formEnable(false);
    }

    function hideEditMode() {
        window.location.reload();
    }

    //Update workFlow funtion
    function updateWorkFlow(Id) {
        let name = $('#editMode .name').val();
        let description = $('#editMode .description').val();
        let chkbxWorkFlowActive = $('#editMode .chkbxWorkFlowActive').prop('checked');
        let chkbxisCritical = $('#editMode .chkbxisCritical').prop('checked');

        if ((!validateForm(name, true, 'nameFullName')) || (!validateForm(description, true, 'DescriptionErrorMessage')))
            return false;

        $.ajax({
            url: '/WorkFlows/UpdateWorkFlow',
            type: 'POST',
            data: {
                id : Id,
                name: name,
                description: description,
                isactive: chkbxWorkFlowActive,
                isCritical: chkbxisCritical,
            },
            success: function (resp) {
                if (resp.responseCode === 2) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Success',
                        text: 'Workflow updated successfully!',
                        confirmButtonText: 'OK',
                        timer: 10000,
                    }).then(()=> {
                        window.location.reload();
                    });
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: 'An error occurred while updating the workflow. Please enter valied data.',
                        confirmButtonText: 'OK',
                    });
                }
            },
            error: function () {
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: 'An unexpected error occurred. Please try again later.',
                    confirmButtonText: 'OK',
                });
            }
        });
    }

    function formEnable(bool) {
        document.getElementById('editMode').querySelectorAll('.editFormFields').forEach(function (element) {
            element.disabled = bool;
        });
    }
</script>

Zenith/Views/SecurityGroup/_FieldsPermissions.cshtml
@model IEnumerable<Zenith.BLL.DTO.FieldsDTO>
<table class="table table-bordered" style="width:128%">
    <thead class="bg-primary text-white text-center text-nowrap">
        <tr>
            <th><b>Window Name</b></th>
            <th>Section Name</th>
            <th>Tab Name</th>
            <th>Field Name</th>
            <th>Allow To View</th>
            <th>Allow To Edit</th>
            <th>Allow to Delete</th>
        </tr>
    </thead>
    <tbody>
        @{
            string windowName = "";
            foreach(var fields in Model)
            {
                if (windowName != fields.WindowName) 
                {
                    windowName = fields.WindowName;
                    // Render the main window row
                    <tr data-fieldid="" data-windowname="@fields.WindowName">
                        <td class="text-center"> @fields.WindowName</td>
                        <td class="text-center"></td>
                        <td class="text-center"></td>
                        <td class="text-center"></td>
                        <td class="text-center">
                            <input type="checkbox" class="actioncheckbox-view" id="actioncheckboxView{@fields.FieldName}" data-windowname="@fields.WindowName" />
                        </td>
                        <td class="text-center">
                            <input type="checkbox" class="actioncheckbox-edit" id="actioncheckboxEdit{@fields.FieldName}" data-windowname="@fields.WindowName" />
                        </td>
                        <td class="text-center">
                            <input type="checkbox" class="actioncheckbox-delete" id="actioncheckboxDelete{@fields.FieldName}" data-windowname="@fields.WindowName" />
                        </td>
                    </tr>
                }

                // Render the record rows
                <tr data-fieldid="@fields.FieldId" data-windowname="@fields.WindowName">
                    <td class="text-center"> @fields.WindowName</td>
                    <td class="text-center">@fields.SectionName</td>
                    <td class="text-center">@fields.TabName </td>
                    <td class="text-center">@fields.FieldName </td>

                    <td class="text-center">
                        <input type="checkbox" class="actioncheckbox-view" data-windowname="@fields.WindowName" />
                    </td>
                    <td class="text-center">
                        <input type="checkbox" class="actioncheckbox-edit" data-windowname="@fields.WindowName" />
                    </td>
                    <td class="text-center">
                        <input type="checkbox" class="actioncheckbox-delete" data-windowname="@fields.WindowName"  />
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Zenith/Views/SecurityGroup/_FieldsPermissionsEditAndView.cshtml
@model IEnumerable<Zenith.BLL.DTO.FieldsDTO>
<table class="table table-bordered" style="width:128%">
    <thead class="bg-primary text-white text-center text-nowrap">
        <tr>
            <th><b>Window Name</b></th>
            <th>Section Name</th>
            <th>Tab Name</th>
            <th>Field Name</th>
            <th>Allow To View</th>
            <th>Allow To Edit</th>
            <th>Allow to Delete</th>
        </tr>
    </thead>
    <tbody>
        @{
            string windowName = "";
            foreach(var fields in Model)
            {
                if (windowName != fields.WindowName) 
                {
                    windowName = fields.WindowName;
                    // Render the main window row
                    <tr data-fieldid="" data-windowname="@fields.WindowName">
                        <td class="text-center"> @fields.WindowName</td>
                        <td class="text-center"></td>
                        <td class="text-center"></td>
                        <td class="text-center"></td>
                        <td class="text-center">
                            <input type="checkbox" class="editFormFields actioncheckbox-view" id="actioncheckboxView{@fields.FieldName}" data-windowname="@fields.WindowName" />
                        </td>
                        <td class="text-center">
                            <input type="checkbox" class="editFormFields actioncheckbox-edit" id="actioncheckboxEdit{@fields.FieldName}" data-windowname="@fields.WindowName" />
                        </td>
                        <td class="text-center">
                            <input type="checkbox" class="editFormFields actioncheckbox-delete" id="actioncheckboxDelete{@fields.FieldName}" data-windowname="@fields.WindowName" />
                        </td>
                    </tr>
                }

                // Render the record rows
                <tr data-fieldid="@fields.FieldId" data-windowname="@fields.WindowName">
                    <td class="text-center"> @fields.WindowName</td>
                    <td class="text-center">@fields.SectionName</td>
                    <td class="text-center">@fields.TabName </td>
                    <td class="text-center">@fields.FieldName </td>

                    <td class="text-center">
                        <input type="checkbox" class="editFormFields actioncheckbox-view" data-windowname="@fields.WindowName" value="@fields.IsView" checked="@fields.IsView" />
                    </td>
                    <td class="text-center">
                        <input type="checkbox" class="editFormFields actioncheckbox-edit" data-windowname="@fields.WindowName" value="@fields.IsEdit" checked="@fields.IsEdit" />
                    </td>
                    <td class="text-center">
                        <input type="checkbox" class="editFormFields actioncheckbox-delete" data-windowname="@fields.WindowName" value="@fields.IsDelete" checked="@fields.IsDelete" />
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Zenith/Views/SecurityGroup/_SecurityGroupList.cshtml
@model IEnumerable<Zenith.BLL.DTO.SecurityGroupsDTO>

<table class="table table-bordered" style="width:128%">
    <thead class="bg-primary text-white text-center text-nowrap">
        <tr>
            <th><input type="checkbox" id="parntVendorChkbxId" onchange="selectAllChkbxChangeEvent(this)" /></th>
            <th><b>Security Group Name</b></th>
            <th><b>Security Group Code</b></th>
            <th><b>Description</b></th>
            <th><b>Created By</b></th>
            <th><b>Created Date & Time </b></th>
            <th><b>IsActive</b></th>
            <th><b>Last Edited User</b></th>
            <th><b>Last Edited Date & Time</b></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var sGroups in Model)
        {
            <tr>
                <td class="text-center">
                    <input type="checkbox" value="@sGroups.Id" UserId="@sGroups.Id" ID="sGroupsCheckBox" class="actionCheckboxes" />
                </td>
                <td class="text-center">
                    @*   <a title="View" target="_blank" class="nav-link" asp-controller="SecurityGroup" asp-action="SecurityGroupTemplate" asp-route-securityGroupId="@sGroups.Id">
                        @sGroups.Name
                    </a> *@
                    <a title="View" target="_blank" class="nav-link" asp-controller="SecurityGroup" asp-action="EditAndViewSecurityGroup" asp-route-securityGroupId="@sGroups.Id">
                        @sGroups.Name
                    </a>
                </td>
                <td class="text-center">@sGroups.SecurityGroupCode</td>
                <td class="text-center">@sGroups.Description</td>
                <td class="text-center">@sGroups.CreatedByName</td>
                <td class="text-center">@sGroups.CreatedOn</td>
                <td class="text-center">@(sGroups.IsActive ? "Y" : "N")</td>
                <td class="text-center">@sGroups.ModifiedByName</td>
                <td class="text-center">@sGroups.ModifiedOn</td>

            </tr>
        }
    </tbody>
</table>

Zenith/Views/SecurityGroup/_vendorOfficer.cshtml
@model IEnumerable<Zenith.BLL.DTO.FieldsDTO>
<table class="table table-bordered" style="width:128%">
    <thead class="bg-primary text-white text-center text-nowrap">
        <tr>
            <th><b>Window Name</b></th>
            <th>Section Name</th>
            <th>Tab Name</th>
            <th>Field Name</th>
            <th>Allow To View</th>
            <th>Allow To Edit</th>
            <th>Allow to Delete</th>
        </tr>
    </thead>
    <tbody>
        @{
            string windowName = "";
            foreach(var fields in Model)
            {
                if (windowName != fields.WindowName) 
                {
                    windowName = fields.WindowName;
                    // Render the main window row
                    <tr data-fieldid="" data-windowname="@fields.WindowName">
                        <td class="text-center"> @fields.WindowName</td>
                        <td class="text-center"></td>
                        <td class="text-center"></td>
                        <td class="text-center"></td>
                        <td class="text-center">
                            <input type="checkbox" class="actioncheckbox-view" id="actioncheckboxView{@fields.FieldName}" data-windowname="@fields.WindowName" />
                        </td>
                        <td class="text-center">
                            <input type="checkbox" class="actioncheckbox-edit" id="actioncheckboxEdit{@fields.FieldName}" data-windowname="@fields.WindowName" />
                        </td>
                        <td class="text-center">
                            <input type="checkbox" class="actioncheckbox-delete" id="actioncheckboxDelete{@fields.FieldName}" data-windowname="@fields.WindowName" />
                        </td>
                    </tr>
                }

                // Render the record rows
                <tr data-fieldid="@fields.FieldId" data-windowname="@fields.WindowName">
                    <td class="text-center"> @fields.WindowName</td>
                    <td class="text-center">@fields.SectionName</td>
                    <td class="text-center">@fields.TabName </td>
                    <td class="text-center">@fields.FieldName </td>

                    <td class="text-center">
                        <input type="checkbox" class="actioncheckbox-view" data-windowname="@fields.WindowName" />
                    </td>
                    <td class="text-center">
                        <input type="checkbox" class="actioncheckbox-edit" data-windowname="@fields.WindowName" />
                    </td>
                    <td class="text-center">
                        <input type="checkbox" class="actioncheckbox-delete" data-windowname="@fields.WindowName"  />
                    </td>
                </tr>
            }
        }
    </tbody>
</table>